# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 661, 211))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 230, 351, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_analysis = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_analysis.setFont(font)
        self.pushButton_analysis.setObjectName("pushButton_analysis")
        self.verticalLayout_2.addWidget(self.pushButton_analysis)
        self.label_words = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_words.setObjectName("label_words")
        self.verticalLayout_2.addWidget(self.label_words)
        self.label_most = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_most.setObjectName("label_most")
        self.verticalLayout_2.addWidget(self.label_most)
        self.label_least = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_least.setObjectName("label_least")
        self.verticalLayout_2.addWidget(self.label_least)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(380, 230, 291, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_search_word = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_search_word.setObjectName("lineEdit_search_word")
        self.verticalLayout.addWidget(self.lineEdit_search_word)
        self.pushButton_search = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_search.setFont(font)
        self.pushButton_search.setObjectName("pushButton_search")
        self.verticalLayout.addWidget(self.pushButton_search)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(230, 230, 230);\n"
"border-color: rgb(153, 153, 153);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text Analyzer"))
        self.pushButton_analysis.setText(_translate("MainWindow", "Analysis"))
        self.label_words.setText(_translate("MainWindow", "Total number of words in the text:"))
        self.label_most.setText(_translate("MainWindow", "The most repeated word in the text:"))
        self.label_least.setText(_translate("MainWindow", "The least repeated word in the text:"))
        self.pushButton_search.setText(_translate("MainWindow", "Search"))
